# Generated by Django 4.1.3 on 2023-02-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hide_email',
            field=models.BooleanField(default=True),
        ),
    ]
