# Generated by Django 4.1.3 on 2023-03-02 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='title',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='publicchatroom',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='users who are connected to the chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
