# Generated by Django 4.1.3 on 2023-02-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='coding', max_length=50),
        ),
    ]
